package com.franosch.paul.solver;

public enum SolvingStrategy {

    NEAREST_NEIGHBOUR_HEURISTIC,
    ALL_STARTING_NODES_NEAREST_NEIGHBOUR_HEURISTIC,
    TRAVERSABLE_ORIENTED_WEIGHTED_NEAREST_NEIGHBOUR_HEURISTIC

}
